- server_script.sh
The `sed` command requires a value for the flag `-i`. If this is missing, the whole `sed` command will fail. Consequently the `docker-compose.product.yml` will not be updated with the correct database settings, hence the failed authentication.
> Bug fix: FATAL: password authentication failed for user xxxx

- .github/workflows/release.yml
- back/Dockerfile
- Forcing Python 3.7 to avoid SemLock error on DO/Render 
Since this is a release candidate, I am not pushing this to latest just yet.
> v1.2.17 rc

- back/admin/resources/models.py
- back/admin/sequences/models.py
- back/admin/sequences/templates/sequence.html
- back/admin/sequences/tests.py
- back/admin/sequences/views.py
- back/admin/templates/tests.py
- back/admin/templates/urls.py
- back/admin/templates/views.py
- back/organization/models.py
- back/slack_bot/tests.py
- back/slack_bot/views.py
- Server returned a 500 error when duplicating. This has been fixed.
- Some minor speed improvements. 
- Avoided name change when duplicating (normally it would add "(duplicate)")
- Fix randomly failing slack test (ordering issue)
> Fix: sequence duplication

- back/admin/sequences/emails.py
- back/admin/sequences/tests.py
Allow people to use variables in the email subject of items in the sequence.
> Add email subject var support

- back/admin/integrations/models.py
- back/admin/people/templates/_new_hire_settings_menu.html
- back/admin/people/tests.py
If user has already started then remove this option as it would show a 404 in most cases anyway. 
People could work around this (by visiting the url directly) and that's okay.
Also make POST the default for integrations (small change, shouldn't impact anything)
> Remove preboarding send menu option

- back/admin/people/forms.py
- back/admin/people/new_hire_views.py
- back/admin/people/templates/_new_hire_settings_menu.html
- back/admin/people/templates/trigger_preboarding_notification.html
- back/admin/people/tests.py
- back/users/emails.py
fixes #196 
- Fix not being able to send email when text messages are not set up
- Fix CSRF token missing from send first day email form
- Allow admins to enter a custom email address for preboarding email
> Fix sending preboarding email, first day email and use custom email

- back/supervisord.conf
According to Gunicorn documentation the default value of `--access-logfile` is None, so we are missing the Gunicorn's logs.
one solution is to change the `--access-logfile` value,
e.g. `--access-logfile '-' `
'-' means log to stdout.
https://docs.gunicorn.org/en/stable/settings.html#logging
> add --access-logfile

- back/user_auth/urls.py
I got a 500 error after a successful reset password with the error below:
```django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_complete' not found. 'password_reset_complete' is not a valid view function or pattern name.```
I did a little bit of research about what happened to me, and I got to this, the name for the `PasswordResetCompleteView ` path should be `password_reset_complete ` instead of `password_reset_done`.
https://docs.djangoproject.com/en/4.0/topics/auth/default/#django.contrib.auth.views.PasswordResetCompleteView
> Edit password/reset_change/done/ name

- back/admin/integrations/models.py
This is kind of hard to explain but there is a bug in the `_replace_vars` function that will delete an unknown tag, at line 87 when `new_hire.personalize` function calls.
e.g. we have a `TEAM_ID` that we want to read from a web portal (just like the `manifest.json` in the docs), the `TEAM_ID` has saved in params but the new_hire.personalize will delete the `{{TEAM_ID}}` after that there is no `{{TEAM_ID}}`.
What I did is that I put the `params` alongside the `extra_args` in the `personalize`.
> _replace_vars function

- docs/Deployment.md
Managed to deploy the app without the need for the Caddy extras. Something to note is that I had already created the database using the original script, so I'm didn't thoroughly test the database creation using the proposed non-caddy approach. Hope people find this useful.
> Non-Caddy deployment.

- back/organization/views.py
- back/slack_bot/slack_resource.py
- back/slack_bot/tests.py
- back/slack_bot/views.py
- Speed up notifications list with `select_related`
- When resource has one page item and one question, it would still show the "next" button when the course was completed. It will now show "close" instead.
- When a course was completed and a user clicked on the button again, it would reset the steps, which would mess up the status bar in the admin panel.
> Speed up notifications list and fix slack resources dialog

- back/slack_bot/utils.py
This sets the limit from `100` to `1000`. If there are more than 1000 channels, then we would need to set up pagination.
> Feat: Fetch more slack channels

- back/admin/people/forms.py
- back/admin/to_do/templates/upload_field.html
This allows admins to directly add the department and the profile picture to the new hire when creating / editing them.
> Add profile picture and department to new hire forms

- back/misc/s3.py
URLs are now valid for almost 7 days instead of 1 hour. This could cause issues in Slack, since messages aren't updated and links would just expire. 7 days is still not ideal, but that's the max of presigned urls.
> Fix: short S3 url valid time

- back/back/templatetags/settings_values.py
- back/misc/s3.py
- back/organization/tests.py
fixes #236 
Allow boto to search for environment variables by itself (except for the region, endpoint and signature) to add the option to not use key/secret, but a profile instead.
> Allow authentication with AWS profile for file down/upload

- back/admin/sequences/tests.py
For some reason, the `form` attribute from the integration factory gets cleared at some point in the tests. Running only the `sequences` tests works without issue, but running all tests errors. Overwriting that locally now to make tests pass.
> Fix failing tests due to not having `form` in `integration`

- back/back/templatetags/settings_values.py
This actually requires an additional permission (`headBucket`) and that might break the functionality for people that have not added that, so I am removing it now.
> Fix: remove S3 check before enabling

- back/admin/people/forms.py
- back/admin/people/tests.py
- back/new_hire/templates/new_hire_base.html
- back/new_hire/tests.py
- back/new_hire/views.py
- back/users/models.py
fixes #253 
This will limit a buddy/manager to a manager/admin/slack user. We can still allow a Slack user as they have the option to check tasks off through the Slack app.
To do:
> Fix error when viewing new hire tasks as admin without startday

- back/back/settings.py
REST_FRAMEWORK_ACTIVE is no longer available in Django-axes. so it's better to remove it.
> Remove REST_FRAMEWORK_ACTIVE

- back/locale/es/LC_MESSAGES/django.po
Fixed a minor misspelling in *Delete* translation, it saw: Eliminar, must to be: Eliminar and the word Trigger is translated as "Dtenoar" but this is most related to explosive events, the correct one is "Activar"that is related to an action to start a movement or step.
Minor fix.
> Minor bug fixes in spanish translation.

- back/admin/people/templates/new_hire_progress.html
- back/admin/people/templates/new_hires.html
- back/new_hire/templates/new_hire_resource_detail.html
Fixes #299 
The progress bar didn't show up if the locale changed. 66.66% would turn to 66,66% and that doesn't work in HTML/CSS. It is now rounded to a full number as the decimals aren't important anyway.
> Fix progress bar not showing up

- back/admin/integrations/models.py
- back/admin/integrations/tests.py
- back/admin/people/new_hire_views.py
- back/admin/people/tests.py
- back/users/templates/admin_base.html
- back/users/templates/login.html
We now get a good error message when something would fail in the integrations part:
Secret values get replaced to avoid accidental exposure of keys/secrets.
This will need a revamp at some point (maybe a separate page for errors?). If we get HTML back, then it would quickly fill up the page. Most apis will return an error in JSON though and not HTML.
> Add error to failed integration

- back/back/settings.py
- back/misc/s3.py
- docs/Deployment.md
- Update the documentation to show that role/profile authentication is possible as well.
- Change `AWS_REGION` -> `AWS_DEFAULT_REGION` (with fallback, so it's not a breaking change)
> Update object storage docs

- back/Pipfile
- back/Pipfile.lock
- back/back/settings.py
Used to be used for Django/Vuejs combo, but never got removed from the application after the migration to normal Django templates.
> Remove custom cors headers options

- back/user_auth/tests.py
- back/user_auth/views.py
* Adding fallback support to read roles from ID Token which is JWT format
* Taking the roles from the JWT based on the OIDC_ROLE_PATH_IN_RETURN
* Added test to validate the role mapping
> Adding ID Token roles mapping

- back/back/settings.py
Fixes docker deployments which would use an internal url instead as the default
fixes #319
> Set default csrf trusted origin to fix docker deployment

- back/organization/management/commands/reset_timed_triggers_last_check.py
- back/organization/tests.py
- back/supervisord-dev.conf
When a dev has not used their environment for a while, the `timed_triggers` function will take a long time to complete. Potentially timing out the task. 
To avoid this, there is a command now, which will run when supervisor starts to reset the last check field to now.
This will only work for the development setup, obviously not on production as it could skip tasks.
> Reset timed triggers check for when developing to avoid timeout of worker

- back/pytest.ini
Fixes:
```
organization/tests.py:218
/app/organization/tests.py:218: PytestUnknownMarkWarning: Unknown pytest.mark.no_run_around_tests - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/
mark.html                                                                                                                                                                                                                              
@pytest.mark.no_run_around_tests 
```
> Fix unknown mark warning from pytest

- back/organization/templates/initial_setup.html
- back/users/templates/no_login_base.html
From this:
To this:
Color is hardcoded to the default (when creating the org). Hard coding is fine in this case as the page will only show once when setting up.
> Fix button poorly visible on setup

- back/slack_bot/tests.py
- back/slack_bot/views.py
Fixing `KeyError` on "email" when a bot user joins the team and the setting to automatically create new hires when someone joins the slack team is turned on. Likely not an option that is used much, so that's why it probably went under the radar for so long.
> Fix KeyError on "email" when bot joins (which has no email address)

- back/user_auth/views.py
Due to bug #337 where SSO is doing lookup by email in case sensitive way (when the DB is always lowercase), I added the lower function to match emails by lowercase as well.
No test was written, just run isort, black and flake8
> convert email to lowercase

- back/admin/sequences/forms.py
To avoid errors later on, we should make assigned to required (if custom user is picked) and also make comment required (otherwise an error could pop up when sending a notification about the task).
> Make assigned to and comment required

- app.json
`hobby` is not available anymore, so we are switching to basic (the eco ones sleep, which is not recommended for the worker).
> Heroku change dyno to basic

- back/admin/integrations/models.py
- back/admin/integrations/serializers.py
- back/admin/integrations/tests.py
- docs/Integrations.md
Part of https://github.com/chiefonboarding/ChiefOnboarding/issues/354
Allows users to specify an attribute from an integration response (third party API) to be saved directly to the user (new hire). This will allow admins to use a previously saved value later on in the sequence/integration.
> Store data from response for reuse in integrations

- back/admin/sequences/models.py
In some cases it could happen that conditions got merged into an incorrect block. This could only happen when there were already overlapping to do conditions assigned to a new hire.
> Fix potential incorrect assignment of to do condition

- back/admin/integrations/models.py
It would sometimes still fail if the "json" function was not in the response. This will catch everything and just fall back to an empty dict.
> Make saving json from response fail safe

- back/new_hire/templates/_content.html
- back/new_hire/templates/_render_list.html
Fix content list rendering.
Inner items weren't rendering, but are now:
> Fix content list rendering

- back/admin/people/new_hire_views.py
- back/admin/people/templates/new_hire_detail.html
Forgot to implement a way to show the integrations and the admin tasks on the new hire page. This fixes that.
> Fix showing integrations on new hire page

- back/users/models.py
- back/users/tests.py
- docs/Integrations.md
This will allow users to add the current access status of all integrations in any of the content boxes or integrations.
> Add access as context variable

- back/admin/people/templates/user_delete.html
It was broken as it was showing up old integration checks. The for loop was placed incorrectly and was not noticeable with only one active integration.
> Fix reloading integrations on user delete

- back/admin/integrations/models.py
- back/admin/people/templates/_new_hire_settings_menu.html
- back/admin/sequences/models.py
- back/organization/models.py
- back/organization/utils.py
- back/users/models.py
- back/users/tests.py
New hires can have a manager/buddy assigned to them. These can then be used in content boxes (by using `{{ manager }}` or `{{ manager_email }}` or similar ones for a buddy) or they can be used for admin tasks or external messages in sequences to assign tasks to or send messages to.
When a new hire gets assigned a sequences that has those references and the new hire does not have a manager, then those will (silently) fail. In the case of content, it will just display nothing. For admin tasks, this will fail the creation of an admin task. 
In most cases, the manager/buddy will be filled for most people, so this will likely not happen often. Though, as a precaution, it will now display a button if that's the case (which leads to the profile page to update the new hire):
> Add check for manager and buddy assigned to user where required

- back/admin/sequences/templates/_sequence_templates_list.html
- back/admin/sequences/templates/sequence.html
- back/users/templates/admin_base.html
Added extra visual feedback for dragging in the sequence page by changing cursor to grabbing, adding a tooltip to the "Create new item" and doing negative color if a drag is not possible.
Also refactored some of the JS code to improve maintainability and make it easier to extend with additional validations and types.
> Sequence - Added dragging feedback & minor JS refactoring

- back/admin/sequences/templates/_sequence_templates_list.html
Todo is focussed on new hire (also based on the start date), so this is broken. Temporarily removing it.
> Disable todo in offboarding sequences

- back/admin/integrations/views.py
`object.id` didn't exist in template, so it was printing an empty string instead.
> Manist live update: Fix error when passing integration id

- back/admin/integrations/views.py
It couldn't compare the `integration.expiring` value as it creates a mock item (which doesn't get saved, so no new value was added).
This will first check if it needs to be renewed (and will renew if necessary), so this will be skipped on the actual test call.
The builder is still in beta, so forgoing adding tests right now.
> Fix missing expiring key for integration builder

- back/admin/integrations/forms.py
- back/admin/integrations/tests.py
This removes the initial values to not show the secrets in the form to any user.
> Clean fields to not show secret values

- back/admin/people/access_views.py
- back/admin/people/templates/_user_access_card.html
- docs/Integrations.md
This was undocumented, but you can add `fail_when_4xx_response_code` to the revoke request to make it fail. 
It will now also show the error in the card when revoking/creating doesn't work.
> Show error when access can not be given

- back/admin/integrations/models.py
In some cases, the password would turn up as an empty string and would therefore replace a lot of text with "Secret value for". This is now fixed.
> Fix empty string being replaced

- back/admin/people/templates/_toggle_button_hardware.html
- back/admin/people/templates/add_hardware.html
- back/admin/people/templates/colleague_update.html
- back/admin/people/tests.py
- back/admin/people/urls.py
- back/admin/people/views.py
This adds a button on the colleagues detail page to manually add hardware to a user. This will not create to do items for any other colleagues to fulfill this. This is intended to be used for existing colleagues that already have hardware, which just need to be registered.
> Allow manually adding hardware to user

- back/admin/integrations/builder_views.py
- back/admin/integrations/templates/manifest_test/execute.html
- back/admin/integrations/utils.py
> Fix not being able to update builder due to unexpected type
