back/sequences/emails.py
back/sequences/models.py
back/users/templates/email/base.html
front/components/general/editor/Editor.vue

Feat: adding extra email fields

---

back/badges/views.py
back/preboarding/views.py
back/to_do/views.py

The content part did not get duplicated for some templates.

Fix: bug in duplicating content

---

.github/workflows/release.yml

This will be deployed to the 'deploy' branch and is then easier to use for deploying.
- Needs updates to the docs

Feat: Auto build Vue/Nuxt source into static files

---

.github/workflows/release.yml
back/requirements.txt
back/sequences/views.py
back/users/views.py
front/components/admin/sequence/Form.vue
front/components/admin/sequence/modals/ExternalMessageModal.vue
requirements.txt

- Show error message when trying to send Slack test message without Slack account attached
- Fix showing preboarding preview part in a sequence
- Fix Slack syncing issue
- Update Django dep to newest version
- Update Docker version number (routine task)
- Fix showing old data in sequences (when adding a new one)

Several bug fixes

---

.github/workflows/release.yml
back/sequences/emails.py
back/sequences/models.py

Fix for sending correct info in email

---

.github/workflows/release.yml
back/user_auth/serializers.py
front/store/sequences.js

Fix email header and removing external messages

---

back/locale/fr/LC_MESSAGES/django.po

French translations of django.po

French translations

---

back/locale/es/LC_MESSAGES/django.po

Adding the Spanish translations to the `back/locale/es/LC_MESSAGES/django.po` file.

Add Spanish translation

---

back/locale/tr/LC_MESSAGES/django.po

Credits: [xubeyb](https://github.com/chiefonboarding/ChiefOnboarding/commits?author=xubeyb)

Turkish translations

---

back/locale/de/LC_MESSAGES/django.po
back/locale/fr/LC_MESSAGES/django.po
back/locale/tr/LC_MESSAGES/django.po

[LC_MESSAGES\django.po] minor fixes in  django.po for de , tr and fe

Minor fixes for language files [LC_MESSAGES\django.po] 

---

back/admin/integrations/forms.py
back/admin/sequences/templates/_item_form.html
back/admin/sequences/templates/sequence.html

I will add testing later for this when I do create a more thorough test of the integrations area.

Add error messages to integration form

---

.github/workflows/release.yml
app.json
heroku.yml

This was still set to the v2.0 repo instead of the master branch.
Bonus fix: attempted to fix the auto docker image creation on PR.

Fix Heroku deploy url

---

back/manage.py

use set_password() to save the admin password encrypted. otherwise, the password will save as plain text.

Encrypt admin/demo account password

---

back/admin/people/new_hire_views.py
back/admin/people/templates/new_hire_detail.html
back/admin/people/tests.py

These will now show up on new hire detail page. They will become green when a new hire has completed one.

Add to do conditions to new hire detail page

---

back/admin/sequences/templates/sequence.html

Incorrect link on delete button

Fix sequence delete button

---

back/admin/integrations/models.py
back/admin/resources/forms.py
back/slack_bot/tasks.py
back/static/js/resources.js

- Fix: sequence block when not having execute notification
- Fix: missing title on course and filter properly
- Fix: course upload files/images and add embed option

Fix sequence notification and course reminder

---

back/admin/sequences/forms.py
back/admin/sequences/tasks.py
back/admin/sequences/templates/sequence.html
back/admin/templates/views.py

- Remove unnecessary print statement
- Avoid modal taking over screen when editing a condition after adding one

Multiple sequence fixes

---

back/admin/sequences/models.py
back/admin/sequences/views.py
back/admin/settings/forms.py

- Remove unique validation as you couldn't upgrade a new hire account to an admin
- Add sequence order to always show them in the correct time based order.

Fix unique validation and add sequence order

---

back/admin/integrations/models.py
back/admin/integrations/views.py
back/admin/settings/templates/settings_integrations.html
back/back/templatetags/settings_values.py

- Not adding code directly into manifest
- Disable oauth button when authenticated

Integration improvements

---

.github/workflows/tests.yml
README.md

Codecov is failing a lot, so testing out coveralls now.

Replace codecov with coveralls

---

back/admin/people/new_hire_views.py
back/admin/people/templates/new_hire_add.html
back/admin/people/templates/new_hire_detail.html
back/admin/people/tests.py
back/admin/people/urls.py
back/admin/sequences/models.py
back/admin/sequences/tests.py
back/locale/de/LC_MESSAGES/django.po
back/locale/es/LC_MESSAGES/django.po
back/locale/fr/LC_MESSAGES/django.po
back/locale/jp/LC_MESSAGES/django.po
back/locale/nl/LC_MESSAGES/django.po
back/locale/pt/LC_MESSAGES/django.po
back/locale/tr/LC_MESSAGES/django.po
back/new_hire/tests.py
back/organization/models.py
back/organization/tests.py
back/users/models.py

Feat: remove sequence from new hire

---

back/api/serializers.py
back/api/tests.py
back/api/urls.py
back/api/views.py
docs/API.md

Note: this will make breaking changes to the API!

Allow creating any user from API

---

back/back/settings.py
docs/Deployment.md

Allow configurable settings and add `forwarded_for`.

Update axes settings

---

back/admin/people/forms.py

Fix manager/buddy translations

---

back/admin/people/forms.py
back/admin/people/tests.py

Fix adding new department to new hire

---

back/locale/es/LC_MESSAGES/django.po

Fixed the "Trigger"translation in spanish

Fixed more Trigger strings

---

back/new_hire/templates/_content.html

Fixed extension info to display uploaded video to minio or s3
Added code to show embed video from youtube or vimeo

Added code for embed content

---

back/admin/people/new_hire_views.py
back/admin/people/tests.py

Fix filter for finding sequences that will not be triggered. It should be gte not lte

Fix new_hire_views.py

---

back/static/js/tabler.js

Only allow to close modal by clicking on the button

---

README.md

This PR adds Elestio as  deployment option along with others
closes #372

feat: Adding Elestio as deployment option

---

back/admin/integrations/models.py

- Avoid the circular import and reference task directly (also avoids task could not be found)
- Don't save the response if we got an error, just save an empty dictionary

A couple small fixes for integrations

---

back/admin/people/templates/new_hires.html

This will add a message to the table when there are no new hires.

Fix empty new hires table

---

back/admin/people/access_views.py
back/admin/people/new_hire_views.py
back/admin/people/templates/_profile_image.html
back/admin/people/views.py
back/users/templates/admin_base.html

Using the `get_user_model` seems to overrule the `user` variable in the admin template, so I have changed it to `request.user`.

Fix user variable on access pages

---

back/admin/integrations/forms.py
back/admin/integrations/models.py
back/admin/integrations/templates/manifest_test.html
back/admin/integrations/templates/manifest_test/_key_value_form.html
back/admin/integrations/templates/manifest_test/_method.html
back/admin/integrations/templates/manifest_test/_name_desc_form.html
back/admin/integrations/urls.py
back/admin/integrations/views.py
back/admin/settings/templates/token_create.html
back/static/js/manifest.js
back/users/templates/admin_base.html

Live manifest builder (beta)

---

back/admin/integrations/exceptions.py
back/admin/integrations/mixins.py
back/admin/integrations/models.py
back/admin/integrations/views.py
back/admin/people/views.py

- fix error when getting a response that is unexpected (not JSON)
- fix error when trying to edit a sync item

Fix integration builder issues

---

back/admin/integrations/models.py

Sometimes we get HTML back from a server and no JSON, so we want to make sure we can parse the JSON.

Fix tracker if invalid JSON

---

back/admin/people/templates/_profile_image.html
back/new_hire/templates/new_hire_base.html
back/users/templates/admin_base.html

Fix user profile images

---

.ci_env
.example_env
.github/workflows/tests.yml
back/back/.env.example
docker-compose.yml
docs/development.md

Move to environment file instead of using inline configuration.

Update docker secret keys management

---

back/admin/people/templates/new_hire_detail.html

Fix timezone on new hire detail page

---

back/locale/de/LC_MESSAGES/django.po

#472 Better german for the subject in the "Welcome preboarding mail"

Update django.po for german users

---

back/fixtures/welcome_message.json

Or is there a reason, that some welcome messages have this space as first character?

Remove unnecessary spaces in welcome messages

---

docs/howto.md

Should be two and not three. Or am I missing something...?

Fix typo in howto.md

---

back/users/templates/admin_base.html

Update changelog link

---

back/admin/admin_tasks/forms.py
back/admin/admin_tasks/models.py
back/locale/nl/LC_MESSAGES/django.po

- Fixes some missing translations in the Dutch translation file
- Made admin to do form translatable

Update dutch translations

---

back/admin/admin_tasks/templates/admin_tasks_all.html
back/admin/admin_tasks/templates/admin_tasks_yours.html

Fix table overflow issue on admin task pages

---

back/new_hire/views.py

Fix to do items not correctly sorted for new hire
